### ISSUE TITLE
no control over startup state

### ISSUE THREAD

**Issue by frueter** [nebukadhezer/rvColorUi#1]
Hi, great tool. Just had a go and noticed the panel is always open on start up.
Would be great for it to remember it's state and/or have a preference.

**Comment by nebukadhezer** [comment]
Hi Frank, 
by preference you mean a menu entry "show gui on startup" ?
I will turn it off by default and will add a setting to override this....
thanks for the input.

**Comment by frueter** [comment]
Yeah, something like that. If I remember right RV has a fairly simple way to read and write settings for this sort of thing.

**Comment by nebukadhezer** [comment]
Hey Frank,

I have added a preference setting, have not made a new release yet, but exchanging the colorUi.py should do.
There are still things without function ... 
cheers

**Comment by frueter** [comment]
great, thank you!

On 27/11/15 6:12 pm, Johannes Hezer wrote:

> Hey Frank,
> 
> I have added a preference setting, have not made a new release yet, 
> but exchanging the colorUi.py should do.
> There are still things without function ...
> cheers
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/nebukadhezer/rvColorUi/issues/1#issuecomment-160044913.

## 

ohufxLogo 50x50 http://www.ohufx.com  _vfx compositing 
http://ohufx.com/index.php/vfx-compositing | *workflow customisation 
and consulting http://ohufx.com/index.php/vfx-customising_ *
